// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_financials_backend.Data;

#nullable disable

namespace student_financials_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("student_financials_backend.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialAid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Scholarships")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tuition")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 2000.00m,
                            Fees = 500.00m,
                            FinancialAid = 5000.00m,
                            Name = "Alice Smith",
                            Scholarships = 2000.00m,
                            Tuition = 10000.00m
                        },
                        new
                        {
                            Id = 2,
                            Balance = 2500.00m,
                            Fees = 550.00m,
                            FinancialAid = 4000.00m,
                            Name = "Bob Johnson",
                            Scholarships = 1500.00m,
                            Tuition = 11000.00m
                        },
                        new
                        {
                            Id = 3,
                            Balance = 3000.00m,
                            Fees = 600.00m,
                            FinancialAid = 3500.00m,
                            Name = "Charlie Brown",
                            Scholarships = 1000.00m,
                            Tuition = 12000.00m
                        },
                        new
                        {
                            Id = 4,
                            Balance = 1800.00m,
                            Fees = 450.00m,
                            FinancialAid = 5500.00m,
                            Name = "David Lee",
                            Scholarships = 3000.00m,
                            Tuition = 9500.00m
                        },
                        new
                        {
                            Id = 5,
                            Balance = 3500.00m,
                            Fees = 500.00m,
                            FinancialAid = 3000.00m,
                            Name = "Emily Chen",
                            Scholarships = 2000.00m,
                            Tuition = 10000.00m
                        },
                        new
                        {
                            Id = 6,
                            Balance = 2700.00m,
                            Fees = 600.00m,
                            FinancialAid = 4500.00m,
                            Name = "Frank Martinez",
                            Scholarships = 1500.00m,
                            Tuition = 11500.00m
                        },
                        new
                        {
                            Id = 7,
                            Balance = 2200.00m,
                            Fees = 550.00m,
                            FinancialAid = 5000.00m,
                            Name = "Grace Kim",
                            Scholarships = 1800.00m,
                            Tuition = 10500.00m
                        },
                        new
                        {
                            Id = 8,
                            Balance = 2900.00m,
                            Fees = 600.00m,
                            FinancialAid = 4000.00m,
                            Name = "Henry Jones",
                            Scholarships = 1000.00m,
                            Tuition = 12000.00m
                        },
                        new
                        {
                            Id = 9,
                            Balance = 1800.00m,
                            Fees = 450.00m,
                            FinancialAid = 5500.00m,
                            Name = "Isabella Thompson",
                            Scholarships = 3000.00m,
                            Tuition = 9500.00m
                        },
                        new
                        {
                            Id = 10,
                            Balance = 2500.00m,
                            Fees = 500.00m,
                            FinancialAid = 3000.00m,
                            Name = "Jackie Ramirez",
                            Scholarships = 2000.00m,
                            Tuition = 10000.00m
                        },
                        new
                        {
                            Id = 11,
                            Balance = 3100.00m,
                            Fees = 550.00m,
                            FinancialAid = 3500.00m,
                            Name = "Katie Patel",
                            Scholarships = 1500.00m,
                            Tuition = 11500.00m
                        },
                        new
                        {
                            Id = 12,
                            Balance = 2400.00m,
                            Fees = 550.00m,
                            FinancialAid = 5000.00m,
                            Name = "Leo Chen",
                            Scholarships = 1800.00m,
                            Tuition = 10500.00m
                        },
                        new
                        {
                            Id = 13,
                            Balance = 2800.00m,
                            Fees = 600.00m,
                            FinancialAid = 4000.00m,
                            Name = "Maria Rodriguez",
                            Scholarships = 1000.00m,
                            Tuition = 12000.00m
                        },
                        new
                        {
                            Id = 14,
                            Balance = 2100.00m,
                            Fees = 450.00m,
                            FinancialAid = 5500.00m,
                            Name = "Nathan Lee",
                            Scholarships = 3000.00m,
                            Tuition = 9500.00m
                        },
                        new
                        {
                            Id = 15,
                            Balance = 3300.00m,
                            Fees = 500.00m,
                            FinancialAid = 3000.00m,
                            Name = "Olivia Kim",
                            Scholarships = 2000.00m,
                            Tuition = 10000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
